### PR TITLE
Properly Lockable Lecterns

### PR DESCRIPTION
**Pull request by doublehelix457**
Lock a Lectern with [Private]. A player can then read the contents of the book, but cannot take the book from the lectern.

Additionally, Lecterns were added to the default config generation as well

### CODE REVIEW

**Review by brunyman — APPROVED** [review]
Good stuff

**Comment by doublehelix457** [comment]
So... This was closed abruptly... Any Reason why?

**Comment by phoenixlzx** [comment]
I have no impression why this is closed, may be due to an error. @Librazy shall review this PR and decide if it can be merged.

**Comment by phoenixlzx** [comment]
Okay I just remembered it was because we have updated the branches.
Please open another PR to the new corresponding branch.

Thanks.

**Comment by doublehelix457** [comment]
Sounds good, will do

**Pull request closed without merging**
